### ISSUE TITLE
Multiple Stops [Feature Request?]

### ISSUE THREAD

**Issue by overomari** [jugler/MMM-OneBusAway#5]
Love the module!
Is it configured to handle multiple stops and multiple buses per stop?

Would it also be possible to have it display the name of the stop if there are multiple stopids listed

Thanks!

**Comment by jugler** [comment]
Hey thanks!
Its not coded to handle multiple stops, on my use case I check it on the bus stop that takes me to work, it does support multiple buses per stop.
I don't think I want to code multiple stops, since I wouldn't use it, but feel free to submit a PR if you want :)
